manifest:
  self:
    path: .

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: ncs
      revision: v3.0.2
      path: nrf
      import: true
